define canopy model 
(         

        model
        (
            size [3.58 0.03 0.04 ]
            pose [0.0 -0.02 1.9 0.0]
            color "green"         
        )

        model
        (
            size [0.08 0.08 0.08 ]
            pose [1.0 0.0 1.82 0.0]
            color "yellow"         
        )

        model
        (
            size [0.08 0.08 0.08 ]
            pose [0.1 0.0 1.82 0.0]
            color "yellow"         
        )

        model
        (
            size [0.08 0.08 0.08 ]
            pose [-0.8 0.0 1.82 0.0]
            color "yellow"         
        )



model
(
size [5.08 0.08 0.04 ]
pose [0.0 0.0 1.9 0.0]
color "burlywood"
)
# Base
 size [0 0 0]
color "green"
stack_children 0
gui_nose 0
obstacle_return 0
)
