define bigBin actor 
(         
    #size 3 x 2 x 1.5 (metre)

    #2 metre side

    model
    (
         size [ 0.1 2 0.33 0]
         pose [ 1.5 0 0.1 0 ]
         color "burlywood"
    )
    model
    (
         size [ 0.1 2 0.33 0]
         pose [ 1.5 0 0.45 0 ]
         color "burlywood"
    )
    model
    (
         size [ 0.1 2 0.33 0]
         pose [ 1.5 0 0.80 0 ]
         color "burlywood"
    )

    model
    (
         size [ 0.1 2 0.33 0]
         pose [ -1.5 0 0.1 0 ]
         color "burlywood"
    )
    model
    (
         size [ 0.1 2 0.33 0]
         pose [ -1.5 0 0.45 0 ]
         color "burlywood"
    )
    model
    (
         size [ 0.1 2 0.33 0]
         pose [ -1.5 0 0.80 0 ]
         color "burlywood"
    )

    #3 metre side
    model
    (
         size [ 3 0.1 0.33 0]
         pose [ 0 1 0.1 0 ]
         color "burlywood"
    )
    model
    (
         size [ 3 0.1 0.33 0]
         pose [ 0 1 0.45 0 ]
         color "burlywood"
    )
    model
    (
         size [ 3 0.1 0.33 0]
         pose [ 0 1 0.80 0 ]
         color "burlywood"
    )
    model
    (
         size [ 3 0.1 0.33 0]
         pose [ 0 -1 0.1 0 ]
         color "burlywood"
    )
    model
    (
         size [ 3 0.1 0.33 0]
         pose [ 0 -1 0.45 0 ]
         color "burlywood"
    )
    model
    (
         size [ 3 0.1 0.33 0]
         pose [ 0 -1 0.80 0 ]
         color "burlywood"
    )

    #bottom
    model
    (
         size [ 3 0.66 0.1 0]
         pose [ 0 -0.66 0.1 0 ]
         color "burlywood"
    )
    model
    (
         size [ 3 0.66 0.1 0]
         pose [ 0 0 0.1 0 ]
         color "burlywood"
    )
    model
    (
         size [ 3 0.66 0.1 0]
         pose [ 0 0.66 0.1 0 ]
         color "burlywood"
    )
    #legs
    model
    (
        size [ 0.1 2 0.1 ]
        pose [ 0 0 0 0]
        color "burlywood"
    )
    model
    (
        size [ 0.1 2 0.1 ]
        pose [ -1.4 0 0 0]
        color "burlywood"
    )

    model
    (
        size [ 0.1 2 0.1 ]
        pose [ 1.4 0 0 0]
        color "burlywood"
    )



    # Base
	size [0 0 0]
	color "burlywood"
	
)
