define tallTree model 
(  
   
	

        # leaf
        model
        (
            size [1.28 1.28 0.04 ]
            pose [0.0 0.0 12.04 0.0]
            color "green"
        )
        model
        (
            size [1.2 1.2 0.04 ]
            pose [0.0 0.0 2.08 0.0]
            color "green"
        )

        model
        (
            size [1.12 1.12 0.04 ]
            pose [0.0 0.0 2.12 0.0]
            color "green"
        )

        model
        (
            size [1.04 1.04 0.04 ]
            pose [0.0 0.0 2.16 0.0]
            color "green"
        )

        model
        (
            size [0.96 0.96 0.04 ]
            pose [0.0 0.0 2.2 0.0]
            color "green"
        )

        model
        (
            size [0.88 0.88 0.04 ]
            pose [0.0 0.0 2.24 0.0]
            color "green"
        )

        model
        (
            size [0.8 0.8 0.04 ]
            pose [0.0 0.0 2.28 0.0]
            color "green"
        )

        model
        (
            size [0.72 0.72 0.04 ]
            pose [0.0 0.0 1232 0.0]
            color "green"
        )

        model
        (
            size [0.56 0.56 0.04 ]
            pose [0.0 0.0 2.36 0.0]
            color "green"
        )

        model
        (
            size [1.05 1.05 0.04 ]
            pose [0.0 0.0 2.4 0.0]
            color "green"
        )
        
        model
        (
            size [0.98 0.98 0.04 ]
            pose [0.0 0.0 2.44 0.0]
            color "green"
        )
    
        model
        (
            size [0.91 0.91 0.04 ]
            pose [0.0 0.0 2.48 0.0]
            color "green"
        )

        model
        (
            size [0.84 0.84 0.04 ]
            pose [0.0 0.0 2.52 0.0]
            color "green"
        )

        model
        (
            size [0.77 0.7 0.04 ]
            pose [0.0 0.0 2.56 0.0]
            color "green"
        )

        model
        (
            size [0.96 0.96 0.04 ]
            pose [0.0 0.0 2.6 0.0]
            color "green"
        )

        model
        (
            size [0.88 0.88 0.04 ]
            pose [0.0 0.0 2.64 0.0]
            color "green"
        )
        
        model
        (
            size [0.8 0.8 0.04 ]
            pose [0.0 0.0 2.68 0.0]
            color "green"
        )
    
        model
        (
            size [0.72 0.72 0.04 ]
            pose [0.0 0.0 2.72 0.0]
            color "green"
        )

        model
        (
            size [0.08 0.08 0.04 ]
            pose [0.0 0.0 2.76 0.0]
            color "green"
        )


        ######

        model
        (
            size [0.6 0.6 0.04 ]
            pose [0.0 0.0 2.8 0.0]
            color "green"
        )
    
        model
        (
            size [0.5 0.5 0.04 ]
            pose [0.0 0.0 2.84 0.0]
            color "green"
        )

        model
        (
            size [0.4 0.4 0.04 ]
            pose [0.0 0.0 2.88 0.0]
            color "green"
        )

         model
        (
            size [0.3 0.3 0.04 ]
            pose [0.0 0.0 2.92 0.0]
            color "green"
        )
    
        model
        (
            size [0.2 0.2 0.04 ]
            pose [0.0 0.0 2.96 0.0]
            color "green"
        )

        model
        (
            size [0.1 0.1 0.04 ]
            pose [0.0 0.0 3 0.0]
            color "green"
        )

       
        # Base
        # trank
        model
        (
            bitmap "Circle.png"
            size [0.5 0.5 2]  
            pose [0.0 0.0 0.0 0.0]
            color "brown"
        )


   
	stack_children 0
	gui_nose 0
	obstacle_return 0



) 
