define tree model 
(  
        # trank
	model
	(
		size [0.16 0.16 1.04]  
                pose [0.0 0.0 0.0 0.0]
		color "brown"
	)

        # leaf
        model
        (
            size [0.72 0.72 0.04 ]
            pose [0.0 0.0 1.04 0.0]
            color "green"
        )
        model
        (
            size [0.64 0.64 0.04 ]
            pose [0.0 0.0 1.08 0.0]
            color "green"
        )

        model
        (
            size [0.56 0.56 0.04 ]
            pose [0.0 0.0 1.12 0.0]
            color "green"
        )

        model
        (
            size [0.48 0.48 0.04 ]
            pose [0.0 0.0 1.16 0.0]
            color "green"
        )

        model
        (
            size [0.40 0.40 0.04 ]
            pose [0.0 0.0 1.2 0.0]
            color "green"
        )

        model
        (
            size [0.32 0.32 0.04 ]
            pose [0.0 0.0 1.24 0.0]
            color "green"
        )

        model
        (
            size [0.24 0.24 0.04 ]
            pose [0.0 0.0 1.28 0.0]
            color "green"
        )

        model
        (
            size [0.16 0.16 0.04 ]
            pose [0.0 0.0 1.32 0.0]
            color "green"
        )

        model
        (
            size [0.56 0.56 0.04 ]
            pose [0.0 0.0 1.36 0.0]
            color "green"
        )

 model
        (
            size [0.49 0.49 0.04 ]
            pose [0.0 0.0 1.4 0.0]
            color "green"
        )
        
        model
        (
            size [0.42 0.42 0.04 ]
            pose [0.0 0.0 1.44 0.0]
            color "green"
        )
    
        model
        (
            size [0.35 0.35 0.04 ]
            pose [0.0 0.0 1.48 0.0]
            color "green"
        )

        model
        (
            size [0.28 0.28 0.04 ]
            pose [0.0 0.0 1.52 0.0]
            color "green"
        )

        model
        (
            size [0.21 0.21 0.04 ]
            pose [0.0 0.0 1.56 0.0]
            color "green"
        )

        model
        (
            size [0.40 0.40 0.04 ]
            pose [0.0 0.0 1.6 0.0]
            color "green"
        )

        model
        (
            size [0.32 0.32 0.04 ]
            pose [0.0 0.0 1.64 0.0]
            color "green"
        )
        
        model
        (
            size [0.24 0.24 0.04 ]
            pose [0.0 0.0 1.68 0.0]
            color "green"
        )
    
        model
        (
            size [0.16 0.16 0.04 ]
            pose [0.0 0.0 1.72 0.0]
            color "green"
        )

        model
        (
            size [0.08 0.08 0.04 ]
            pose [0.0 0.0 1.76 0.0]
            color "green"
        )

       
        
        # post
        model
        (
            size [0.08 0.08 1.9]
            pose [0.0 0.4 0.0 0.0]
            color "burlywood"
        )
       
        # Base
	size [0 0 0]
	color "grey"
	stack_children 0
	gui_nose 0
	obstacle_return 0
	
) 
